In [19]:
import os
import sys
sys.path.insert(0, os.path.abspath('..'))

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

from utils.load_config import load_config
from data_loader.data_loader_wk1 import DataLoaderWeek1
from models.model_wk1 import ModelWeek1

In [26]:
config = load_config("../config/config_wk1.yml")
config

{'image_size': 50,
 'epochs': 100,
 'data_sets': {'week1_data_train': {'image_data': ['../data/Week1/2dft.dat',
    '../data/Week1/2dft.i.dat'],
   'label_data': '../data/Week1/2dftn.dat'}},
 'data_train_split': 0.8,
 'data_validation_split': 0.8,
 'data_batch_size': 32,
 'data_num_classes': 3}

In [3]:
data_loader = DataLoaderWeek1(config)

train_data_set, test_data_set, validation_data_set = data_loader.load_data_set("week1_data_train")

In [4]:
model_wk1 = ModelWeek1(config)
model = model_wk1.get_uncompiled_model()
model = model_wk1.compile_model(model)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 48, 48, 32)        320       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 46, 46, 64)        18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 23, 23, 64)        0         
_________________________________________________________________
dropout (Dropout)            (None, 23, 23, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 33856)             0         
_________________________________________________________________
dense (Dense)                (None, 128)               4333696   
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0

In [27]:
epochs = config.get("epochs", 100)

model.fit(
    train_data_set,
    steps_per_epoch=50,
    epochs=epochs,
    validation_data=validation_data_set,
    validation_steps=50,
    verbose=1,
)

Train for 50 steps, validate for 50 steps
Epoch 1/100
50/50 [==============================] - 9s 183ms/step - loss: 1.0435 - accuracy: 0.6175 - val_loss: 1.0396 - val_accuracy: 0.6125
Epoch 2/100
50/50 [==============================] - 9s 185ms/step - loss: 1.0381 - accuracy: 0.6300 - val_loss: 1.0359 - val_accuracy: 0.6225
Epoch 3/100
50/50 [==============================] - 10s 199ms/step - loss: 1.0333 - accuracy: 0.6531 - val_loss: 1.0326 - val_accuracy: 0.6219
Epoch 4/100
50/50 [==============================] - 9s 179ms/step - loss: 1.0313 - accuracy: 0.6431 - val_loss: 1.0271 - val_accuracy: 0.6388
Epoch 5/100
50/50 [==============================] - 9s 181ms/step - loss: 1.0274 - accuracy: 0.6456 - val_loss: 1.0233 - val_accuracy: 0.6469
Epoch 6/100
50/50 [==============================] - 9s 181ms/step - loss: 1.0222 - accuracy: 0.6625 - val_loss: 1.0200 - val_accuracy: 0.6506
Epoch 7/100
50/50 [==============================] - 9s 182ms/step - loss: 1.0201 - accuracy: 0.655

In [7]:
model_wk1.save_model_and_weights_to_disk(model, "model.json", "model.h5")

In [24]:
correct_labels = []
predicted_labels = []

for image, label in test_data_set:
    predicted = model.predict(image)

    for val in label.numpy(): correct_labels.append(val[0])
    for val in predicted: predicted_labels.append(np.argmax(val))
    # predicted_labels.append(predicted)

In [25]:
print(confusion_matrix(correct_labels, predicted_labels))

[[199   0   0]
 [ 25 153  12]
 [211   0   0]]
